[project]
name = "Crash Bandicoot 3: Warped"
slug = "crash-bandicoot-3-warped"
retail_id = "SCUS-94244"
region = "USA"
implementation_state = "release_candidate_prepared"

[release]
version = "0.1.0"
status = "candidate"
target_date = "2026-09-07"

[framework]
repository = "https://github.com/Alexbeav/psxrecomp"
commit = "4d6f6c987ccc1f90e31966dc203ccd221545e013"
tree = "0d30e0073f43c8012be99812394b5db46d0adb08"
recomp_ui_commit = "be8ac1d03ee19d55394b5a5f2d9d1506edd56659"
accepted_private_commit = "63446a28111a21a0cb7e8b5106c3614c898fc4b5"

[bios]
required = true
profile = "SCPH1001"
size = 524288
sha256 = "71af94d1e47a68c11e8fdb9f8368040601514a42a5a399cda48c7d3bff1e99d3"

[validation]
windows_package = "not_run"
linux_gameplay = "not_run"
macos_gameplay = "not_run"

[retail_identity]
disc_count = 1
serials = ["SCUS-94244"]
